name: Deploy Next.js Project

on:
  push:
    branches:
      - main # 监听 main 分支的 push 事件

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出仓库代码

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 设置 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      # 步骤1：文件同步 - 使用 appleboy/scp-action
      - name: Sync files to server
        uses: appleboy/scp-action@v0.1.7  # 使用 SCP 专门用于文件传输
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # source 和 target 参数在这里是有效的
          source: ".next/static/,public/" 
          # 注意：请根据您的 Next.js 构建产物调整 source 路径
          target: "/www/wwwroot/Personal-Website-frontend"
          # 注意：scp-action v0.1.7 的参数有所不同，请参考文档
          # rsync: true # v0.1.7 默认支持 rsync

      # 步骤2：远程执行命令 - 使用 appleboy/ssh-action
      - name: Run commands on server
        uses: appleboy/ssh-action@v0.1.10  # 使用最新版本执行脚本
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # 最新版本的 ssh-action 主要只接受 script 参数
          script: |
            echo "文件传输完成，正在重启服务..."