name: Deploy Next.js Project

on:
  push:
    branches:
      - main # 监听 main 分支的 push 事件

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出仓库代码

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 设置 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Deploy to server
        # 这是一个示例，您需要根据您的部署方式修改
        # 比如，使用rsync通过SSH部署
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./.next/static/,./public/,./.next/standalone/"
          target: "/www/wwwroot/Personal-Website-frontend" # 您服务器上存放项目的路径
          script: |
            # 停止旧服务，更新文件，启动新服务
            echo "Deployment successful!"